import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Ribbon from "@/components/Ribbon";
import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Panther Landscaping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-0 p-0"
      >
        <Ribbon />
        <Header />
          <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
